import type { Metadata } from 'next';
import './globals.css';
import { DmSans, JetBrainsMono } from '@/common/constants/fonts';
import { Providers } from '@/components/layouts/Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body suppressHydrationWarning className={`${DmSans.variable} ${JetBrainsMono.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
