import type { Metadata } from "next";
import "./globals.css";
import { DmSans, JetBrainsMono } from "@/common/constants/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${DmSans.variable} ${JetBrainsMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
